# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ubuntu:22.04
            options: -v ${{ github.workspace }}:/mnt
            run: |
                cd /mnt
                apt-get update
                DEBIAN_FRONTEND=noninteractive apt-get install -y pandoc texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra python3-ipython python3-pip ipython3 git nodejs npm
                pip install Jinja2
                npm install -g markdown-styles
                sh build.sh slides/*.md
                mkdir build/
                cp slides/*.pdf build/
                git config --global --add safe.directory '*'
                ipython3 publish.ipy
                cp -r resources/ build/resources/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
